package view;

import java.awt.Color;

/**
 * Esta clase permite crear un panel para representar actividades, aquí se
 * implementa los métodos necesarios para la modificar la interfaz
 *
 * @author Bladimir Minga
 * @author Steveen Ganchozo
 * @version 17/02/2020/A
 */
public class pnlActivity extends javax.swing.JPanel {

    /**
     * Constructor para la crear el componente pnlActivity que será utilizado en
     * la vista frmMain
     *
     * @param intNActivity Esta variable de tipo entero se lo utiliza para el
     * componente lblNActivity con la finalidad de asignar el número
     * correspondiente a la actividad.
     * @param strNameActivity Esta variable de tipo string se lo utiliza para el
     * componente lblNameActivity con la finalidad de asignar el nombre
     * correspondiente a la actividad.
     */
    public pnlActivity(int intNActivity, String strNameActivity) {
        initComponents();
        lblNActivity.setText(String.valueOf(intNActivity));
        txtNameActivity.setText(strNameActivity);
    }//Cierre del método constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNActivity = new javax.swing.JLabel();
        lblCompleteActivity = new javax.swing.JLabel();
        txtNameActivity = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        lblNActivity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNActivity.setText("Actividad 1");

        lblCompleteActivity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCompleteActivity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompleteActivity.setText("INCOMPLETED");

        txtNameActivity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNameActivity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNameActivity.setText("name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCompleteActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNameActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblNActivity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(txtNameActivity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCompleteActivity)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCompleteActivity;
    private javax.swing.JLabel lblNActivity;
    private javax.swing.JLabel txtNameActivity;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que cambia el color de fondo al componente y que asigna el texto
     * "COMPLETED" a la actividad
     */
    public void setCompletActivity() {
        this.setBackground(Color.GREEN);
        lblCompleteActivity.setText("COMPLETED");
    }//Cierre del método setCompleteActivity
}//Cierre de la clase pnlActivity
